obj-y += flw_dev_list.o
ifdef CONFIG_SPL_BUILD
obj-$(CONFIG_FLASHWRITER) += flw_sf.o
obj-$(CONFIG_FLASHWRITER) += flw_mmc.o
obj-$(CONFIG_FLASHWRITER) += flw_nor.o
obj-$(CONFIG_FLASHWRITER) += flw_main.o
endif
