#ifndef __MPW7705_H
#define __MPW7705_H

#include <linux/sizes.h>

#define CONFIG_MPW7705
#define CONFIG_SYS_TEXT_BASE	0x40000
#define CONFIG_SPL_TEXT_BASE	0x40018
#define CONFIG_SYS_UBOOT_BASE	CONFIG_SYS_TEXT_BASE

#ifdef CONFIG_SPL_BUILD
#define CONFIG_SYS_MONITOR_BASE CONFIG_SPL_TEXT_BASE
#else
#define CONFIG_SYS_MONITOR_BASE CONFIG_SYS_TEXT_BASE
#endif

#define CONFIG_ENV_SIZE         0x80
#define CONFIG_SPL_STACK        0x80000
#define CONFIG_SPL_FRAMEWORK

#define CONFIG_SYS_DDR_BASE     CONFIG_SYS_TEXT_BASE
#define CONFIG_SYS_SDRAM_BASE   CONFIG_SYS_DDR_BASE
#define CONFIG_SYS_DDR_SIZE     SZ_1G
#define CONFIG_SYS_LOAD_ADDR    CONFIG_SYS_TEXT_BASE

#define CONFIG_SYS_MAX_FLASH_BANKS      0
#define CONFIG_SYS_MALLOC_LEN           0x8000
#define CONFIG_CHIP_SELECTS_PER_CTRL    2
#define CONFIG_DIMM_SLOTS_PER_CTLR      2

#define CONFIG_USE_STDINT 1

#endif /* __MPW7705_H */
