#ifndef __MPW7705_H
#define __MPW7705_H

#include <linux/sizes.h>

#define CONFIG_SYS_SPL_MALLOC_START 0x40000000
#define CONFIG_SYS_SPL_MALLOC_SIZE  0x20000

#define CONFIG_SYS_INIT_RAM_ADDR		0x40000000
#define CONFIG_SYS_INIT_RAM_SIZE		0x100000

#define CONFIG_SYS_GBL_DATA_OFFSET	(CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)
#define CONFIG_SYS_INIT_SP_OFFSET	CONFIG_SYS_GBL_DATA_OFFSET


#define CONFIG_MPW7705
#define CONFIG_SPL_TEXT_BASE	0x40018
#define CONFIG_SYS_UBOOT_BASE	CONFIG_SYS_TEXT_BASE
#define CONFIG_SYS_UBOOT_START  CONFIG_SYS_TEXT_BASE

#ifdef CONFIG_SPL_BUILD
#define CONFIG_SYS_MONITOR_BASE CONFIG_SPL_TEXT_BASE
#else
#define CONFIG_SYS_MONITOR_BASE CONFIG_SYS_TEXT_BASE
#endif

#define CONFIG_ENV_SIZE         0x80
#define CONFIG_SPL_STACK        0x38000
#define CONFIG_SPL_FRAMEWORK

#define CONFIG_SYS_MALLOC_LEN           0x20000

#define CONFIG_SYS_DDR_BASE     CONFIG_SYS_TEXT_BASE
#define CONFIG_SYS_SDRAM_BASE   CONFIG_SYS_DDR_BASE
#define CONFIG_SYS_DDR_SIZE     SZ_128M
#define CONFIG_SYS_LOAD_ADDR    CONFIG_SYS_TEXT_BASE

#define CONFIG_SYS_MEMTEST_START	CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_MEMTEST_END		(CONFIG_SYS_MONITOR_BASE - \
					 CONFIG_ENV_SIZE - \
					 CONFIG_SYS_MALLOC_LEN -	\
					 0x10000)
#define CONFIG_SYS_DRAM_TEST
                     

#define CONFIG_SYS_MAX_FLASH_BANKS      0
#define CONFIG_CHIP_SELECTS_PER_CTRL    2
#define CONFIG_DIMM_SLOTS_PER_CTLR      2

#define CONFIG_USE_STDINT 1
#define CONFIG_SPL_SPI_LOAD
#define CONFIG_SPL_EDCL_LOAD

#define BOOT_DEVICE_SPI 11
#define BOOT_DEVICE_EDCL 12

#define BOOT_ROM_HOST_MODE 0xfffc0178

#define CONFIG_SYS_SPI_U_BOOT_OFFS      0x20000
#define CONFIG_SYS_SPI_CLK 100000000

#define CONFIG_PL01X_SERIAL
#define CONFIG_BAUDRATE 115200
/*#define CONFIG_DEBUG_UART_SKIP_INIT 1*/

#define CONFIG_SYS_PBSIZE 1024

#endif /* __MPW7705_H */
