#include "mivem_regs_access.h"

#define CRG_DDR_PLL_STATE           0x000
#define CRG_DDR_PLL_CTRL            0x004
#define CRG_DDR_PLL_DIVMODE         0x008
#define CRG_DDR_WR_LOCK             0x00C
#define CRG_DDR_RST_MON             0x010
#define CRG_DDR_RST_CTRL            0x014
#define CRG_DDR_RST_EN              0x018
#define CRG_DDR_UPD_CK              0x01C
#define CRG_DDR_CKALIGN             0x020

#define CRG_DDR_CKDIVMODE_LSIF      0x100
#define CRG_DDR_CKEN_LSIF           0x104

#define CRG_DDR_CKDIVMODE_HSIF      0x110
#define CRG_DDR_CKEN_HSIF           0x114

#define CRG_DDR_CKDIVMODE_DDR3_1X   0x120
#define CRG_DDR_CKDIVMODE_DDR3_REFCLK 0x120
#define CRG_DDR_CKEN_DDR3_1X        0x124

#define CRG_DDR_CKDIVMODE_DDR3_4X   0x150
#define CRG_DDR_CKEN_DDR3_4X        0x154

//SCTL
#define SCTL_BASE                             0x38000000
#define SCTL_PLL_STATE                        0x004

REG_READ(crg_ddr, CRG_DDR_PLL_STATE, 32)

REG_READ(crg_ddr, CRG_DDR_PLL_CTRL, 32)
REG_WRITE(crg_ddr, CRG_DDR_PLL_CTRL, 32)
REG_SET(crg_ddr, CRG_DDR_PLL_CTRL, 32)
REG_CLEAR(crg_ddr, CRG_DDR_PLL_CTRL, 32)

REG_READ(crg_ddr, CRG_DDR_PLL_DIVMODE, 32)
REG_WRITE(crg_ddr, CRG_DDR_PLL_DIVMODE, 32)
REG_SET(crg_ddr, CRG_DDR_PLL_DIVMODE, 32)
REG_CLEAR(crg_ddr, CRG_DDR_PLL_DIVMODE, 32)

REG_READ(crg_ddr, CRG_DDR_WR_LOCK, 32)
REG_WRITE(crg_ddr, CRG_DDR_WR_LOCK, 32)
REG_SET(crg_ddr, CRG_DDR_WR_LOCK, 32)
REG_CLEAR(crg_ddr, CRG_DDR_WR_LOCK, 32)

REG_READ(crg_ddr, CRG_DDR_RST_MON, 32)
REG_WRITE(crg_ddr, CRG_DDR_RST_MON, 32)
REG_SET(crg_ddr, CRG_DDR_RST_MON, 32)
REG_CLEAR(crg_ddr, CRG_DDR_RST_MON, 32)

REG_READ(crg_ddr, CRG_DDR_RST_CTRL, 32)
REG_WRITE(crg_ddr, CRG_DDR_RST_CTRL, 32)
REG_SET(crg_ddr, CRG_DDR_RST_CTRL, 32)
REG_CLEAR(crg_ddr, CRG_DDR_RST_CTRL, 32)

REG_READ(crg_ddr, CRG_DDR_RST_EN, 32)
REG_WRITE(crg_ddr, CRG_DDR_RST_EN, 32)
REG_SET(crg_ddr, CRG_DDR_RST_EN, 32)
REG_CLEAR(crg_ddr, CRG_DDR_RST_EN, 32)

REG_READ(crg_ddr, CRG_DDR_UPD_CK, 32)
REG_WRITE(crg_ddr, CRG_DDR_UPD_CK, 32)
REG_SET(crg_ddr, CRG_DDR_UPD_CK, 32)
REG_CLEAR(crg_ddr, CRG_DDR_UPD_CK, 32)

REG_READ(crg_ddr, CRG_DDR_CKALIGN, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKALIGN, 32)
REG_SET(crg_ddr, CRG_DDR_CKALIGN, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKALIGN, 32)

REG_READ(crg_ddr, CRG_DDR_CKDIVMODE_LSIF, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKDIVMODE_LSIF, 32)
REG_SET(crg_ddr, CRG_DDR_CKDIVMODE_LSIF, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKDIVMODE_LSIF, 32)

REG_READ(crg_ddr, CRG_DDR_CKEN_LSIF, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKEN_LSIF, 32)
REG_SET(crg_ddr, CRG_DDR_CKEN_LSIF, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKEN_LSIF, 32)

REG_READ(crg_ddr, CRG_DDR_CKDIVMODE_HSIF, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKDIVMODE_HSIF, 32)
REG_SET(crg_ddr, CRG_DDR_CKDIVMODE_HSIF, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKDIVMODE_HSIF, 32)

REG_READ(crg_ddr, CRG_DDR_CKEN_HSIF, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKEN_HSIF, 32)
REG_SET(crg_ddr, CRG_DDR_CKEN_HSIF, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKEN_HSIF, 32)

REG_READ(crg_ddr, CRG_DDR_CKDIVMODE_DDR3_1X, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKDIVMODE_DDR3_1X, 32)
REG_SET(crg_ddr, CRG_DDR_CKDIVMODE_DDR3_1X, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKDIVMODE_DDR3_1X, 32)

REG_READ(crg_ddr, CRG_DDR_CKEN_DDR3_1X, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKEN_DDR3_1X, 32)
REG_SET(crg_ddr, CRG_DDR_CKEN_DDR3_1X, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKEN_DDR3_1X, 32)

REG_READ(crg_ddr, CRG_DDR_CKDIVMODE_DDR3_4X, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKDIVMODE_DDR3_4X, 32)
REG_SET(crg_ddr, CRG_DDR_CKDIVMODE_DDR3_4X, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKDIVMODE_DDR3_4X, 32)

REG_READ(crg_ddr, CRG_DDR_CKEN_DDR3_4X, 32)
REG_WRITE(crg_ddr, CRG_DDR_CKEN_DDR3_4X, 32)
REG_SET(crg_ddr, CRG_DDR_CKEN_DDR3_4X, 32)
REG_CLEAR(crg_ddr, CRG_DDR_CKEN_DDR3_4X, 32)


BEGIN_ENUM( CRG_CPU_REG )
DECLARE_ENUM_VAL( CRG_CPU_PLL_STATE,            0x000 )
DECLARE_ENUM_VAL( CRG_CPU_PLL_CTRL,             0x004 )
DECLARE_ENUM_VAL( CRG_CPU_PLL_DIVMODE,          0x008 )
DECLARE_ENUM_VAL( CRG_CPU_WR_LOCK,              0x00C )
DECLARE_ENUM_VAL( CRG_CPU_RST_MON,              0x010 )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL,             0x014 )
DECLARE_ENUM_VAL( CRG_CPU_RST_EN,               0x018 )
DECLARE_ENUM_VAL( CRG_CPU_UPD_CK,               0x01C )
DECLARE_ENUM_VAL( CRG_CPU_CKALIGN,              0x020 )

DECLARE_ENUM_VAL( CRG_CPU_CKDIVMODE_PPC470S,    0x100 )
DECLARE_ENUM_VAL( CRG_CPU_CKEN_PPC470S,         0x104 )

DECLARE_ENUM_VAL( CRG_CPU_CKDIVMODE_L2C_PLB6,   0x110 )
DECLARE_ENUM_VAL( CRG_CPU_CKEN_L2C_PLB6,        0x114 )

DECLARE_ENUM_VAL( CRG_CPU_CKDIVMODE_PPC_TMR,    0x120 )
DECLARE_ENUM_VAL( CRG_CPU_CKEN_PPC_TMR,         0x124 )

DECLARE_ENUM_VAL( CRG_CPU_CKDIVMODE_LSIF0_A,    0x130 )
DECLARE_ENUM_VAL( CRG_CPU_CKEN_LSIF0_A,         0x134 )

DECLARE_ENUM_VAL( CRG_CPU_CKDIVMODE_AXI,        0x140 )
DECLARE_ENUM_VAL( CRG_CPU_CKEN_AXI,             0x144 )

DECLARE_ENUM_VAL( CRG_CPU_CKDIVMODE_PLB4,       0x150 )

DECLARE_ENUM_VAL( CRG_CPU_CKDIVMODE_DCR,        0x160 )

DECLARE_ENUM_VAL( CRG_CPU_CKEN_DCR,             0x164 )

DECLARE_ENUM_VAL( CRG_CPU_CKDIVMODE_APB,        0x170 )
END_ENUM( CRG_CPU_REG )



REG_READ(crg_cpu, CRG_CPU_PLL_STATE, 32)

REG_READ(crg_cpu, CRG_CPU_PLL_CTRL, 32)
REG_WRITE(crg_cpu, CRG_CPU_PLL_CTRL, 32)
REG_SET(crg_cpu, CRG_CPU_PLL_CTRL, 32)
REG_CLEAR(crg_cpu, CRG_CPU_PLL_CTRL, 32)

REG_READ(crg_cpu, CRG_CPU_PLL_DIVMODE, 32)
REG_WRITE(crg_cpu, CRG_CPU_PLL_DIVMODE, 32)
REG_SET(crg_cpu, CRG_CPU_PLL_DIVMODE, 32)
REG_CLEAR(crg_cpu, CRG_CPU_PLL_DIVMODE, 32)

REG_READ(crg_cpu, CRG_CPU_WR_LOCK, 32)
REG_WRITE(crg_cpu, CRG_CPU_WR_LOCK, 32)
REG_SET(crg_cpu, CRG_CPU_WR_LOCK, 32)
REG_CLEAR(crg_cpu, CRG_CPU_WR_LOCK, 32)

REG_READ(crg_cpu, CRG_CPU_RST_MON, 32)
REG_WRITE(crg_cpu, CRG_CPU_RST_MON, 32)
REG_SET(crg_cpu, CRG_CPU_RST_MON, 32)
REG_CLEAR(crg_cpu, CRG_CPU_RST_MON, 32)

REG_READ(crg_cpu, CRG_CPU_RST_CTRL, 32)
REG_WRITE(crg_cpu, CRG_CPU_RST_CTRL, 32)
REG_SET(crg_cpu, CRG_CPU_RST_CTRL, 32)
REG_CLEAR(crg_cpu, CRG_CPU_RST_CTRL, 32)

REG_READ(crg_cpu, CRG_CPU_RST_EN, 32)
REG_WRITE(crg_cpu, CRG_CPU_RST_EN, 32)
REG_SET(crg_cpu, CRG_CPU_RST_EN, 32)
REG_CLEAR(crg_cpu, CRG_CPU_RST_EN, 32)

REG_READ(crg_cpu, CRG_CPU_UPD_CK, 32)
REG_WRITE(crg_cpu, CRG_CPU_UPD_CK, 32)
REG_SET(crg_cpu, CRG_CPU_UPD_CK, 32)
REG_CLEAR(crg_cpu, CRG_CPU_UPD_CK, 32)

REG_READ(crg_cpu, CRG_CPU_CKALIGN, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKALIGN, 32)
REG_SET(crg_cpu, CRG_CPU_CKALIGN, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKALIGN, 32)

REG_READ(crg_cpu, CRG_CPU_CKDIVMODE_PPC470S, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKDIVMODE_PPC470S, 32)
REG_SET(crg_cpu, CRG_CPU_CKDIVMODE_PPC470S, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKDIVMODE_PPC470S, 32)

REG_READ(crg_cpu, CRG_CPU_CKEN_PPC470S, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKEN_PPC470S, 32)
REG_SET(crg_cpu, CRG_CPU_CKEN_PPC470S, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKEN_PPC470S, 32)

REG_READ(crg_cpu, CRG_CPU_CKDIVMODE_L2C_PLB6, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKDIVMODE_L2C_PLB6, 32)
REG_SET(crg_cpu, CRG_CPU_CKDIVMODE_L2C_PLB6, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKDIVMODE_L2C_PLB6, 32)

REG_READ(crg_cpu, CRG_CPU_CKEN_L2C_PLB6, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKEN_L2C_PLB6, 32)
REG_SET(crg_cpu, CRG_CPU_CKEN_L2C_PLB6, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKEN_L2C_PLB6, 32)

REG_READ(crg_cpu, CRG_CPU_CKDIVMODE_PPC_TMR, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKDIVMODE_PPC_TMR, 32)
REG_SET(crg_cpu, CRG_CPU_CKDIVMODE_PPC_TMR, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKDIVMODE_PPC_TMR, 32)

REG_READ(crg_cpu, CRG_CPU_CKEN_PPC_TMR, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKEN_PPC_TMR, 32)
REG_SET(crg_cpu, CRG_CPU_CKEN_PPC_TMR, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKEN_PPC_TMR, 32)

REG_READ(crg_cpu, CRG_CPU_CKDIVMODE_LSIF0_A, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKDIVMODE_LSIF0_A, 32)
REG_SET(crg_cpu, CRG_CPU_CKDIVMODE_LSIF0_A, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKDIVMODE_LSIF0_A, 32)

REG_READ(crg_cpu, CRG_CPU_CKEN_LSIF0_A, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKEN_LSIF0_A, 32)
REG_SET(crg_cpu, CRG_CPU_CKEN_LSIF0_A, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKEN_LSIF0_A, 32)

REG_READ(crg_cpu, CRG_CPU_CKDIVMODE_AXI, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKDIVMODE_AXI, 32)
REG_SET(crg_cpu, CRG_CPU_CKDIVMODE_AXI, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKDIVMODE_AXI, 32)

REG_READ(crg_cpu, CRG_CPU_CKEN_AXI, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKEN_AXI, 32)
REG_SET(crg_cpu, CRG_CPU_CKEN_AXI, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKEN_AXI, 32)

REG_READ(crg_cpu, CRG_CPU_CKDIVMODE_PLB4, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKDIVMODE_PLB4, 32)
REG_SET(crg_cpu, CRG_CPU_CKDIVMODE_PLB4, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKDIVMODE_PLB4, 32)

REG_READ(crg_cpu, CRG_CPU_CKDIVMODE_DCR, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKDIVMODE_DCR, 32)
REG_SET(crg_cpu, CRG_CPU_CKDIVMODE_DCR, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKDIVMODE_DCR, 32)

REG_READ(crg_cpu, CRG_CPU_CKEN_DCR, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKEN_DCR, 32)
REG_SET(crg_cpu, CRG_CPU_CKEN_DCR, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKEN_DCR, 32)

REG_READ(crg_cpu, CRG_CPU_CKDIVMODE_APB, 32)
REG_WRITE(crg_cpu, CRG_CPU_CKDIVMODE_APB, 32)
REG_SET(crg_cpu, CRG_CPU_CKDIVMODE_APB, 32)
REG_CLEAR(crg_cpu, CRG_CPU_CKDIVMODE_APB, 32)



BEGIN_ENUM( CRG_CPU_RST_MON_FIELD )
DECLARE_ENUM_VAL( CRG_CPU_RST_MON_XRST_i,   2 )
DECLARE_ENUM_VAL( CRG_CPU_RST_MON_XRST_n,   1 )

DECLARE_ENUM_VAL( CRG_CPU_RST_MON_SWRST_i,  1 )
DECLARE_ENUM_VAL( CRG_CPU_RST_MON_SWRST_n,  1 )

DECLARE_ENUM_VAL( CRG_CPU_RST_MON_WDRST_i,  0 )
DECLARE_ENUM_VAL( CRG_CPU_RST_MON_WDRST_n,  1 )
END_ENUM( CRG_CPU_RST_MON_FIELD )


BEGIN_ENUM( CRG_CPU_RST_CTRL_FIELD )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_SWRSTM_i,    9 )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_SWRSTM_n,    1 )

DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_WDRSTM_i,    8 )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_WDRSTM_n,    1 )

DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_RST_DUR_i,   0 )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_RST_DUR_n,   4 )
END_ENUM( CRG_CPU_RST_CTRL_FIELD )

BEGIN_ENUM( CRG_CPU_RST_CTRL_SWRSTM )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_SWRSTM_external, 0b0 )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_SWRSTM_all,      0b1 )
END_ENUM( CRG_CPU_RST_CTRL_SWRSTM )

BEGIN_ENUM( CRG_CPU_RST_CTRL_WDRSTM )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_WDRSTM_external, 0b0 )
DECLARE_ENUM_VAL( CRG_CPU_RST_CTRL_WDRSTM_all,      0b1 )
END_ENUM( CRG_CPU_RST_CTRL_WDRSTM )

BEGIN_ENUM( CRG_CPU_RST_CTRL_RST_DUR )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_8clocks,      0x0 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_12clocks,     0x1 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_16clocks,     0x2 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_24clocks,     0x3 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_32clocks,     0x4 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_48clocks,     0x5 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_64clocks,     0x6 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_96clocks,     0x7 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_128clocks,    0x8 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_192clocks,    0x9 )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_256clocks,    0xA )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_384clocks,    0xB )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_512clocks,    0xC )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_768clocks,    0xD )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_1024clocks,   0xE )
DECLARE_ENUM_VAL(CRG_CPU_RST_CTRL_RST_DUR_1536clocks,   0xF )
END_ENUM( CRG_CPU_RST_CTRL_RST_DUR )



