#ifndef SYSREG_H_
#define SYSREG_H_

#define PL061_DATA_BASE  0x000
#define PL061_DATA       (PL061_DATA_BASE + (0xff << 2))
#define PL061_DIR        0x400
#define PL061_AFSEL      0x420

#define PL022_IMSC  0x014

#define SDIO_SDR_CARD_BLOCK_SET_REG  0x00
#define SDIO_SDR_CTRL_REG            0x04
#define SDIO_SDR_CMD_ARGUMENT_REG    0x08
#define SDIO_SDR_ADDRESS_REG         0x0C
#define SDIO_SDR_ERROR_ENABLE_REG    0x14
#define SDIO_SDR_BUF_TRAN_RESP_REG   0x48
#define SDIO_BUF_TRAN_CTRL_REG       0x50
#define SDIO_SDR_RESPONSE1_REG       0x18
#define SDIO_SDR_RESPONSE2_REG       0x1C
#define SDIO_SDR_RESPONSE3_REG       0x20
#define SDIO_SDR_RESPONSE4_REG       0x24

#define SDIO_DCCR_0                  0x28
#define SDIO_DCSSAR_0                0x2C
#define SDIO_DCDTR_0                 0x34

#define SDIO_DCCR_1                  0x38
#define SDIO_DCDSAR_1                0x40
#define SDIO_DCDTR_1                 0x44

#define SPISDIO_ENABLE           0x300
#define SPISDIO_SDIO_CLK_DIVIDE  0x304
#define SPISDIO_SDIO_INT_STATUS  0x308
#define SPISDIO_SDIO_INT_MASKS   0x30C


#define SPISDIO_SDIO_INT_STATUS_CH0_FINISH  0x01
#define SPISDIO_SDIO_INT_STATUS_CH1_FINISH  0x02
#define SPISDIO_SDIO_INT_STATUS_BUF_FINISH  0x04
#define SPISDIO_SDIO_INT_STATUS_CAR_ERR     0x40
#define SPISDIO_SDIO_INT_STATUS_CMD_DONE    0x20
#define SPISDIO_SDIO_INT_STATUS_TRAN_DONE   0x10

#define	SPISDIO_SPI_IRQMASKS  0x0D8

/*
#define READ_MEM_REG(REG_NAME, REG_OFFSET, REG_SIZE)\
inline static uint##REG_SIZE##_t read_##REG_NAME(uint32_t const base_addr)\
{\
    return *((volatile uint##REG_SIZE##_t*)(base_addr + REG_OFFSET));\
}

#define WRITE_MEM_REG(REG_NAME, REG_OFFSET, REG_SIZE)\
inline static void write_##REG_NAME(uint32_t const base_addr, uint32_t const value)\
{\
    *((volatile uint##REG_SIZE##_t*)(base_addr + REG_OFFSET)) = value;\
}

READ_MEM_REG(PL061_DATA,PL061_DATA,8)
WRITE_MEM_REG(PL061_DATA,PL061_DATA,8)

READ_MEM_REG(PL061_DIR,PL061_DIR,8)
WRITE_MEM_REG(PL061_DIR,PL061_DIR,8)

READ_MEM_REG(PL061_AFSEL,PL061_AFSEL,8)
WRITE_MEM_REG(PL061_AFSEL,PL061_AFSEL,8)


READ_MEM_REG(PL022_IMSC,PL022_IMSC,16);
WRITE_MEM_REG(PL022_IMSC,PL022_IMSC,16);


WRITE_MEM_REG(SDIO_SDR_CTRL_REG,SDIO_SDR_CTRL_REG,32)
READ_MEM_REG(SDIO_SDR_CTRL_REG,SDIO_SDR_CTRL_REG,32)

WRITE_MEM_REG(SDIO_SDR_ERROR_ENABLE_REG,SDIO_SDR_ERROR_ENABLE_REG,32)
READ_MEM_REG(SDIO_SDR_ERROR_ENABLE_REG,SDIO_SDR_ERROR_ENABLE_REG,32)

WRITE_MEM_REG(SDIO_SDR_CMD_ARGUMENT_REG,SDIO_SDR_CMD_ARGUMENT_REG,32)
READ_MEM_REG(SDIO_SDR_CMD_ARGUMENT_REG,SDIO_SDR_CMD_ARGUMENT_REG,32)

WRITE_MEM_REG(SDIO_SDR_BUF_TRAN_RESP_REG,SDIO_SDR_BUF_TRAN_RESP_REG,32)
READ_MEM_REG(SDIO_SDR_BUF_TRAN_RESP_REG,SDIO_SDR_BUF_TRAN_RESP_REG,32)

READ_MEM_REG(SDIO_SDR_RESPONSE1_REG,SDIO_SDR_RESPONSE1_REG,32)
READ_MEM_REG(SDIO_SDR_RESPONSE2_REG,SDIO_SDR_RESPONSE2_REG,32)
READ_MEM_REG(SDIO_SDR_RESPONSE3_REG,SDIO_SDR_RESPONSE3_REG,32)
READ_MEM_REG(SDIO_SDR_RESPONSE4_REG,SDIO_SDR_RESPONSE4_REG,32)

WRITE_MEM_REG(SDIO_DCCR_1,SDIO_DCCR_1,32)
READ_MEM_REG(SDIO_DCCR_1,SDIO_DCCR_1,32)

WRITE_MEM_REG(SDIO_DCDSAR_1,SDIO_DCDSAR_1,32)
READ_MEM_REG(SDIO_DCDSAR_1,SDIO_DCDSAR_1,32)

WRITE_MEM_REG(SDIO_DCDTR_1,SDIO_DCDTR_1,32)
READ_MEM_REG(SDIO_DCDTR_1,SDIO_DCDTR_1,32)

WRITE_MEM_REG(SDIO_SDR_ADDRESS_REG,SDIO_SDR_ADDRESS_REG,32)
READ_MEM_REG(SDIO_SDR_ADDRESS_REG,SDIO_SDR_ADDRESS_REG,32)

WRITE_MEM_REG(SDIO_SDR_CARD_BLOCK_SET_REG,SDIO_SDR_CARD_BLOCK_SET_REG,32)
READ_MEM_REG(SDIO_SDR_CARD_BLOCK_SET_REG,SDIO_SDR_CARD_BLOCK_SET_REG,32)

WRITE_MEM_REG(SDIO_BUF_TRAN_CTRL_REG,SDIO_BUF_TRAN_CTRL_REG,32)
READ_MEM_REG(SDIO_BUF_TRAN_CTRL_REG,SDIO_BUF_TRAN_CTRL_REG,32)


WRITE_MEM_REG(SPISDIO_ENABLE,SPISDIO_ENABLE,32)
READ_MEM_REG(SPISDIO_ENABLE,SPISDIO_ENABLE,32)

READ_MEM_REG(SPISDIO_SDIO_INT_STATUS,SPISDIO_SDIO_INT_STATUS,32)

WRITE_MEM_REG(SPISDIO_SDIO_INT_MASKS,SPISDIO_SDIO_INT_MASKS,32)
READ_MEM_REG(SPISDIO_SDIO_INT_MASKS,SPISDIO_SDIO_INT_MASKS,32)

WRITE_MEM_REG(SPISDIO_SDIO_CLK_DIVIDE,SPISDIO_SDIO_CLK_DIVIDE,32)
READ_MEM_REG(SPISDIO_SDIO_CLK_DIVIDE,SPISDIO_SDIO_CLK_DIVIDE,32)

WRITE_MEM_REG(SPISDIO_SPI_IRQMASKS,SPISDIO_SPI_IRQMASKS,32)
READ_MEM_REG(SPISDIO_SPI_IRQMASKS,SPISDIO_SPI_IRQMASKS,32)
*/

#define CRGCPU__        0x38006000
#define GPIO1__         0x3C03C000
#define LSIF1_MGPIO4__  0x3C064000
#define SDIO__          0x3C06A000
#define SPISDIO__       0x3C06A000
#define GSPI__          0x3C059000

#endif /* SYSREG_H_ */
