#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2010, Thomas Chou <thomas@wytron.com.tw>
# Copyright (C) 2014 Altera Corporation <www.altera.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifdef CONFIG_MPW7705_DDR
obj-$(CONFIG_TARGET_MPW7705) += ddr_init.o timer.o
endif
