/*
 *  Created on: Sep 10, 2015
 *      Author: a.korablinov
 */

#ifndef PPC470S_REG_ACCESS_H_
#define PPC470S_REG_ACCESS_H_

#include "ppc470s_regs.h"

//SPR access
#define READ_SPR_REG(REG)                           \
inline static uint32_t read_##REG(void)                 \
{                                                   \
    uint32_t rval=0;                                \
    asm volatile   (                                \
        "mfspr %0, %1 \n\t"                         \
        :"=r"(rval)                                 \
        :"i"(REG)                                   \
        :                                           \
    );                                              \
    return rval;                                    \
}

#define WRITE_SPR_REG(REG)                          \
inline static void write_##REG(uint32_t const value)\
{                                                   \
    asm volatile   (                                \
        "mtspr %1, %0 \n\t"                         \
        ::"r"(value), "i"(REG)                      \
        :                                           \
    );                                              \
}

inline static void write_SPR_MSR( uint32_t const wval )
{
    mtmsr(wval);
}

inline static uint32_t read_SPR_MSR(void)
{
    return mfmsr();
}

WRITE_SPR_REG(SPR_CTR)
READ_SPR_REG(SPR_CTR)

WRITE_SPR_REG(SPR_LR)
READ_SPR_REG(SPR_LR)

WRITE_SPR_REG(SPR_DCRIPR)
READ_SPR_REG(SPR_DCRIPR)

READ_SPR_REG(SPR_DCDBTRH)

READ_SPR_REG(SPR_DCDBTRL)

WRITE_SPR_REG(SPR_DCESR)
READ_SPR_REG(SPR_DCESR)

READ_SPR_REG(SPR_ICDBDR0)

READ_SPR_REG(SPR_ICDBDR1)

READ_SPR_REG(SPR_ICDBTRH)

READ_SPR_REG(SPR_ICDBTRL)

WRITE_SPR_REG(SPR_ICESR)
READ_SPR_REG(SPR_ICESR)

WRITE_SPR_REG(SPR_IOCCR)
READ_SPR_REG(SPR_IOCCR)

WRITE_SPR_REG(SPR_IOCR1)
READ_SPR_REG(SPR_IOCR1)

WRITE_SPR_REG(SPR_IOCR2)
READ_SPR_REG(SPR_IOCR2)

WRITE_SPR_REG(SPR_DAC1)
READ_SPR_REG(SPR_DAC1)

WRITE_SPR_REG(SPR_DAC2)
READ_SPR_REG(SPR_DAC2)

WRITE_SPR_REG(SPR_DVC1)
READ_SPR_REG(SPR_DVC1)

WRITE_SPR_REG(SPR_DVC2)
READ_SPR_REG(SPR_DVC2)

WRITE_SPR_REG(SPR_DBCR0)
READ_SPR_REG(SPR_DBCR0)

WRITE_SPR_REG(SPR_DBCR1)
READ_SPR_REG(SPR_DBCR1)

WRITE_SPR_REG(SPR_DBCR2)
READ_SPR_REG(SPR_DBCR2)

WRITE_SPR_REG(SPR_DBDR)
READ_SPR_REG(SPR_DBDR)

WRITE_SPR_REG(SPR_DBSR_W)
READ_SPR_REG(SPR_DBSR_RC)
WRITE_SPR_REG(SPR_DBSR_RC)

WRITE_SPR_REG(SPR_IAC1)
READ_SPR_REG(SPR_IAC1)

WRITE_SPR_REG(SPR_IAC2)
READ_SPR_REG(SPR_IAC2)

WRITE_SPR_REG(SPR_IAC3)
READ_SPR_REG(SPR_IAC3)

WRITE_SPR_REG(SPR_IAC4)
READ_SPR_REG(SPR_IAC4)

WRITE_SPR_REG(SPR_XER)
READ_SPR_REG(SPR_XER)

WRITE_SPR_REG(SPR_CSRR0)
READ_SPR_REG(SPR_CSRR0)

WRITE_SPR_REG(SPR_CSRR1)
READ_SPR_REG(SPR_CSRR1)

WRITE_SPR_REG(SPR_DEAR)
READ_SPR_REG(SPR_DEAR)

WRITE_SPR_REG(SPR_ESR)
READ_SPR_REG(SPR_ESR)

WRITE_SPR_REG(SPR_IVOR0)
READ_SPR_REG(SPR_IVOR0)

WRITE_SPR_REG(SPR_IVOR1)
READ_SPR_REG(SPR_IVOR1)

WRITE_SPR_REG(SPR_IVOR2)
READ_SPR_REG(SPR_IVOR2)

WRITE_SPR_REG(SPR_IVOR3)
READ_SPR_REG(SPR_IVOR3)

WRITE_SPR_REG(SPR_IVOR4)
READ_SPR_REG(SPR_IVOR4)

WRITE_SPR_REG(SPR_IVOR5)
READ_SPR_REG(SPR_IVOR5)

WRITE_SPR_REG(SPR_IVOR6)
READ_SPR_REG(SPR_IVOR6)

WRITE_SPR_REG(SPR_IVOR7)
READ_SPR_REG(SPR_IVOR7)

WRITE_SPR_REG(SPR_IVOR8)
READ_SPR_REG(SPR_IVOR8)

WRITE_SPR_REG(SPR_IVOR9)
READ_SPR_REG(SPR_IVOR9)

WRITE_SPR_REG(SPR_IVOR10)
READ_SPR_REG(SPR_IVOR10)

WRITE_SPR_REG(SPR_IVOR11)
READ_SPR_REG(SPR_IVOR11)

WRITE_SPR_REG(SPR_IVOR12)
READ_SPR_REG(SPR_IVOR12)

WRITE_SPR_REG(SPR_IVOR13)
READ_SPR_REG(SPR_IVOR13)

WRITE_SPR_REG(SPR_IVOR14)
READ_SPR_REG(SPR_IVOR14)

WRITE_SPR_REG(SPR_IVOR15)
READ_SPR_REG(SPR_IVOR15)

WRITE_SPR_REG(SPR_IVPR)
READ_SPR_REG(SPR_IVPR)

WRITE_SPR_REG(SPR_MCSRR0)
READ_SPR_REG(SPR_MCSRR0)

WRITE_SPR_REG(SPR_MCSRR1)
READ_SPR_REG(SPR_MCSRR1)

WRITE_SPR_REG(SPR_MCSR_RW)
READ_SPR_REG(SPR_MCSR_RW)
WRITE_SPR_REG(SPR_MCSR_C)

WRITE_SPR_REG(SPR_SRR0)
READ_SPR_REG(SPR_SRR0)

WRITE_SPR_REG(SPR_SRR1)
READ_SPR_REG(SPR_SRR1)

WRITE_SPR_REG(SPR_PMUCC0)
READ_SPR_REG(SPR_PMUCC0)

READ_SPR_REG(SPR_PMUCC0_UR)

WRITE_SPR_REG(SPR_ISPCR)
READ_SPR_REG(SPR_ISPCR)

//WRITE_SPR_REG(SPR_MMUBE0) /*TODO: need to know SPR_MMUBE0 access*/
READ_SPR_REG(SPR_MMUBE0)

//WRITE_SPR_REG(SPR_MMUBE1) /*TODO: need to know SPR_MMUBE1 access*/
READ_SPR_REG(SPR_MMUBE1)

WRITE_SPR_REG(SPR_MMUCR)
READ_SPR_REG(SPR_MMUCR)

WRITE_SPR_REG(SPR_PID)
READ_SPR_REG(SPR_PID)

WRITE_SPR_REG(SPR_RMPD)
READ_SPR_REG(SPR_RMPD)

READ_SPR_REG(SPR_RSTCFG)

WRITE_SPR_REG(SPR_SSPCR)
READ_SPR_REG(SPR_SSPCR)

WRITE_SPR_REG(SPR_USPCR)
READ_SPR_REG(SPR_USPCR)

WRITE_SPR_REG(SPR_CCR0)
READ_SPR_REG(SPR_CCR0)

WRITE_SPR_REG(SPR_CCR1)
READ_SPR_REG(SPR_CCR1)

WRITE_SPR_REG(SPR_CCR2)
READ_SPR_REG(SPR_CCR2)

READ_SPR_REG(SPR_PIR)

READ_SPR_REG(SPR_PVR)

WRITE_SPR_REG(SPR_SPRG0)
READ_SPR_REG(SPR_SPRG0)

WRITE_SPR_REG(SPR_SPRG1)
READ_SPR_REG(SPR_SPRG1)

WRITE_SPR_REG(SPR_SPRG2)
READ_SPR_REG(SPR_SPRG2)

WRITE_SPR_REG(SPR_SPRG3)
READ_SPR_REG(SPR_SPRG3)

READ_SPR_REG(SPR_SPRG3_UR)

WRITE_SPR_REG(SPR_SPRG4)
READ_SPR_REG(SPR_SPRG4)

WRITE_SPR_REG(SPR_SPRG5)
READ_SPR_REG(SPR_SPRG5)

WRITE_SPR_REG(SPR_SPRG6)
READ_SPR_REG(SPR_SPRG6)

WRITE_SPR_REG(SPR_SPRG7)
READ_SPR_REG(SPR_SPRG7)

WRITE_SPR_REG(SPR_SPRG8)
READ_SPR_REG(SPR_SPRG8)

WRITE_SPR_REG(SPR_USPGR0)
READ_SPR_REG(SPR_USPGR0)

WRITE_SPR_REG(SPR_DECAR)
READ_SPR_REG(SPR_DECAR)

WRITE_SPR_REG(SPR_DEC)
READ_SPR_REG(SPR_DEC)

WRITE_SPR_REG(SPR_TBL_W)
READ_SPR_REG(SPR_TBL_R)

WRITE_SPR_REG(SPR_TBU_W)
READ_SPR_REG(SPR_TBU_R)

WRITE_SPR_REG(SPR_TCR)
READ_SPR_REG(SPR_TCR)

WRITE_SPR_REG(SPR_TSR_W)
READ_SPR_REG(SPR_TSR_RC)
WRITE_SPR_REG(SPR_TSR_RC)

#endif /* PPC470S_REG_ACCESS_H_ */
