/**
 *
 */

#ifndef __DDR_MCIF2ARB4_REG_H__
#define __DDR_MCIF2ARB4_REG_H__


#include "reg_field.h"
#include "../../mivem_types.h"


BEGIN_ENUM( MCIF2ARB4_REG )
DECLARE_ENUM_VAL( MCIF2ARB4_MACR,   0x00 )  // 0x00000000
END_ENUM( MCIF2ARB4_REG )

BEGIN_ENUM( MCIF2ARB4_REG_DFLT )
DECLARE_ENUM_VAL( MCIF2ARB4_MACR_DFLT,  0x00000000 )
END_ENUM( MCIF2ARB4_REG_DFLT )

BEGIN_ENUM( MCIF2ARB4_REG_MSK )
DECLARE_ENUM_VAL( MCIF2ARB4_MACR_MSK,   0xF80003FF )
END_ENUM( MCIF2ARB4_REG_MSK )


#endif // __DDR_MCIF2ARB4_REG_H__
